In [3]:
import pandas as pd

# Load the cleaned dataset
df = pd.read_csv("cleaned_crypto_data.csv")

# Check if it loaded correctly
df.head()

,coin,symbol,price,1h,24h,7d,24h_volume,mkt_cap,date
0,Bitcoin,BTC,0.991319,0.022,0.030,0.055,0.610870,7.709915e+11,2022-03-16
1,Ethereum,ETH,0.066584,0.024,0.034,0.065,0.340877,3.271044e+11,2022-03-16
2,Tether,USDT,0.000024,-0.001,-0.001,0.000,1.000000,7.996516e+10,2022-03-16
3,BNB,BNB,0.009303,0.018,0.028,0.004,0.024093,6.404382e+10,2022-03-16
4,USD Coin,USDC,0.000024,-0.001,0.000,-0.000,0.066838,5.222214e+10,2022-03-16

In [4]:
# Convert 'date' to datetime
df['date'] = pd.to_datetime(df['date'])

# Sort by coin and date
df = df.sort_values(['coin', 'date'])

# 7-day moving average
df['price_ma7'] = df.groupby('coin')['price'].transform(lambda x: x.rolling(window=7, min_periods=1).mean())

# 2-day rolling volatility
df['price_volatility'] = df.groupby('coin')['price'].transform(lambda x: x.rolling(window=2, min_periods=1).std())

# Liquidity ratio
df['liquidity_ratio'] = df['24h_volume'] / (df['price'] + 1e-6)

In [5]:
df.to_csv("feature_engineered_crypto.csv", index=False)